# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "usbhid" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

boot.plymouth = {
    enable = true;
    themePackages = [(pkgs.adi1090x-plymouth-themes.override {selected_themes = ["splash"];})];
    theme = "splash";
  };

boot.initrd.systemd.enable = true;
  boot.supportedFilesystems = ["zfs"];
  boot.zfs.allowHibernation = true;
  boot.zfs.forceImportRoot = false;
  boot.zfs.forceImportAll = false;
  services.zfs.autoScrub.enable = true;
  boot.initrd.postDeviceCommands = lib.mkAfter ''
    zfs rollback -r zroot/enc/root@blank
  '';



  fileSystems."/" =
    { device = "zroot/enc/root";
      fsType = "zfs";
	options = ["zfsutil"];
	neededForBoot = true;
    };

  fileSystems."/nix" =
    { device = "zroot/enc/nix";
      fsType = "zfs";
	options = ["zfsutil"];
	neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7A48-75DB";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "zroot/enc/home";
      fsType = "zfs";
	options = ["zfsutil"];
	neededForBoot = true;
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/50f02c1f-0905-430b-8cce-6c01d7fa40d2"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
